name: Flutter app CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  dart:
    permissions:
      contents: read
    uses: famedly/frontend-ci-templates/.github/workflows/dart.yml@main
    with:
      env_file: ".github/workflows/versions.env"
    secrets:
      ssh_key: "${{ secrets.CI_SSH_PRIVATE_KEY }}"
  # master branch should be renamed to main to be able to run this workflow
  # general:
  #   permissions:
  #     contents: read
  #   uses: famedly/frontend-ci-templates/.github/workflows/general.yml@main

